# Generated by Django 4.2.14 on 2024-07-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название соц сети')),
            ],
            options={
                'verbose_name': 'Название соц сети',
                'verbose_name_plural': 'Название соц сети',
            },
        ),
        migrations.CreateModel(
            name='SocialTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на соц сеть')),
                ('related_social_network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.socialnetworkmodel', verbose_name='Название соц сети')),
            ],
            options={
                'verbose_name': 'SocialTask',
                'verbose_name_plural': 'SocialTask',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Задания')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('points', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TaskTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип задания')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Тип задания',
            },
        ),
        migrations.CreateModel(
            name='UserTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('claim', 'Claim'), ('reject', 'Reject')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('timestamp', models.DateTimeField(verbose_name='Дата добавления')),
                ('related_social_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.socialtaskmodel', verbose_name='SocialTask')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'UserTask',
                'verbose_name_plural': 'UserTask',
            },
        ),
        migrations.CreateModel(
            name='TaskModeratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('claim', 'Claim'), ('reject', 'Reject')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('timestamp', models.DateTimeField(verbose_name='Дата добавления')),
                ('related_moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_tasks', to='users.customuser', verbose_name='Модератор')),
                ('related_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskmodel', verbose_name='Задания')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_user_tasks', to='users.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ручная проверка',
                'verbose_name_plural': 'Ручная проверка',
            },
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='related_task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasktypemodel', verbose_name='Тип задания'),
        ),
        migrations.AddField(
            model_name='socialtaskmodel',
            name='related_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskmodel', verbose_name='Задания'),
        ),
    ]
