# Generated by Django 4.2.14 on 2024-07-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskmodel',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='taskmoderatormodel',
            name='related_moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='taskmoderatormodel',
            name='related_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskmodel', verbose_name='Задания'),
        ),
        migrations.AddField(
            model_name='taskmoderatormodel',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='related_task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasktypemodel', verbose_name='Тип задания'),
        ),
        migrations.AddField(
            model_name='socialtaskmodel',
            name='related_social_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.socialnetworkmodel', verbose_name='Название соц сети'),
        ),
        migrations.AddField(
            model_name='socialtaskmodel',
            name='related_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskmodel', verbose_name='Задания'),
        ),
    ]
