# Generated by Django 4.2.14 on 2024-07-29 17:30

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название каталога')),
                ('image', models.ImageField(upload_to=users.models.generate_image_path, verbose_name='Картинка')),
                ('active', models.BooleanField(default=True, verbose_name='доступ')),
            ],
            options={
                'verbose_name': 'Аватарка',
                'verbose_name_plural': 'Аватарка',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('telegram_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('twitter_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter аккаунт')),
                ('youtube_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube аккаунт')),
                ('remaining_invites', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оставшиеся приглашения')),
                ('related_avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.avatarsmodel', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='LanguagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Язык')),
                ('iso_code', models.CharField(max_length=10, unique=True, verbose_name='iso_code')),
                ('active', models.BooleanField(default=True, verbose_name='доступ')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Язык',
            },
        ),
        migrations.CreateModel(
            name='NameWalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название кошелька')),
            ],
            options={
                'verbose_name': 'Название кошелька',
                'verbose_name_plural': 'Название кошелька',
            },
        ),
        migrations.CreateModel(
            name='TonWalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('date', models.DateTimeField(verbose_name='Дата добавления')),
                ('related_name_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nameWallets', to='users.namewalletmodel')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='users.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'TonWallet',
                'verbose_name_plural': 'TonWallet',
            },
        ),
        migrations.CreateModel(
            name='ReferralsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Дата добавления')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма бонуса')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_referrals', to='users.customuser', verbose_name='Пользователь')),
                ('related_user_referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users.customuser', verbose_name='Пользователь реферал')),
            ],
            options={
                'verbose_name': 'Referrals',
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.CreateModel(
            name='ModeratorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Модераторы',
                'verbose_name_plural': 'Модераторы',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='related_languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.languagesmodel', verbose_name='Язык'),
        ),
    ]
