# Generated by Django 4.2.14 on 2024-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
