# Generated by Django 4.2.14 on 2024-07-28 17:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatarsmodel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='avatarsmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='languagesmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='namewalletmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='avatarsmodel',
            name='image',
            field=models.ImageField(default=1, upload_to=users.models.generate_image_path, verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
