# Generated by Django 4.2.14 on 2024-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_avatarsmodel_link_remove_avatarsmodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonwalletmodel',
            name='address',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='адрес'),
            preserve_default=False,
        ),
    ]
