# Generated by Django 4.2.14 on 2024-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tonwalletmodel_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralsmodel',
            options={'verbose_name': 'Referrals', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(verbose_name='Баланс'),
        ),
    ]
